# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iWIFI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iWIFI
#  pod 'ReachabilitySwift'
# pod 'CrossroadRegex'
pod 'KeychainSwift', '~> 7.0'
pod 'Alamofire', '~> 4.0'
end
